import web3 from './web3';

const address = process.env.REACT_APP_SMART_CONTRACT_ATTACHMENT_ADDRESS;

const abi = [{"inputs":[{"internalType":"address","name":"_user_contract","type":"address"},{"internalType":"address","name":"_task_contract","type":"address"}],"stateMutability":"nonpayable","type":"constructor"},{"inputs":[{"internalType":"uint256","name":"","type":"uint256"}],"name":"attachments","outputs":[{"internalType":"uint256","name":"attachment_id","type":"uint256"},{"internalType":"string","name":"attachment_name","type":"string"},{"internalType":"string","name":"attachment_link","type":"string"},{"internalType":"string","name":"deleted","type":"string"},{"internalType":"uint256","name":"task_id","type":"uint256"},{"internalType":"uint256","name":"user_id","type":"uint256"},{"internalType":"uint256","name":"create_at","type":"uint256"},{"internalType":"uint256","name":"update_at","type":"uint256"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"uint256","name":"attachment_id","type":"uint256"},{"internalType":"string","name":"attachment_name","type":"string"},{"internalType":"string","name":"attachment_link","type":"string"},{"internalType":"uint256","name":"task_id","type":"uint256"}],"name":"createAttachment","outputs":[{"internalType":"bool","name":"","type":"bool"}],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"uint256","name":"attachment_id","type":"uint256"}],"name":"deleteAttachment","outputs":[{"internalType":"bool","name":"","type":"bool"}],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"uint256","name":"attachment_id","type":"uint256"}],"name":"findAttachment","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"uint256","name":"attachment_id","type":"uint256"},{"internalType":"string","name":"attachment_name","type":"string"}],"name":"updateAttachment","outputs":[{"internalType":"bool","name":"","type":"bool"}],"stateMutability":"nonpayable","type":"function"}]

let contract = web3 ? new web3.eth.Contract(abi, address) : null

export default contract

