import web3 from './web3';

const address = process.env.REACT_APP_SMART_CONTRACT_LABEL_ADDRESS;

const abi = [{"inputs":[{"internalType":"address","name":"_user_contract","type":"address"},{"internalType":"address","name":"_task_contract","type":"address"}],"stateMutability":"nonpayable","type":"constructor"},{"inputs":[{"internalType":"uint256","name":"label_id","type":"uint256"},{"internalType":"uint256","name":"task_id","type":"uint256"}],"name":"addLabelToTask","outputs":[{"internalType":"bool","name":"","type":"bool"}],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"uint256","name":"label_id","type":"uint256"},{"internalType":"string","name":"label_name","type":"string"},{"internalType":"string","name":"label_color","type":"string"}],"name":"create","outputs":[{"internalType":"bool","name":"","type":"bool"}],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"uint256","name":"label_id","type":"uint256"}],"name":"deleteLabel","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"uint256","name":"label_id","type":"uint256"}],"name":"findLabel","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"uint256","name":"label_id","type":"uint256"}],"name":"getLabelDetailById","outputs":[{"internalType":"uint256","name":"","type":"uint256"},{"internalType":"uint256","name":"","type":"uint256"},{"internalType":"string","name":"","type":"string"},{"internalType":"string","name":"","type":"string"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"getList","outputs":[{"components":[{"internalType":"uint256","name":"label_id","type":"uint256"},{"internalType":"uint256","name":"user_id","type":"uint256"},{"internalType":"string","name":"label_name","type":"string"},{"internalType":"string","name":"label_color","type":"string"}],"internalType":"struct Label.LabelEntity[]","name":"","type":"tuple[]"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"uint256","name":"label_id","type":"uint256"},{"internalType":"uint256","name":"task_id","type":"uint256"}],"name":"removeLabelFromTask","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"uint256","name":"label_id","type":"uint256"},{"internalType":"string","name":"label_name","type":"string"},{"internalType":"string","name":"label_color","type":"string"}],"name":"update","outputs":[{"internalType":"bool","name":"","type":"bool"}],"stateMutability":"nonpayable","type":"function"}]


let contract = web3 ? new web3.eth.Contract(abi, address) : null;

export default contract